# Generated by Django 6.0.2 on 2026-02-18 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('direction', models.CharField(choices=[('ltr', 'Left-to-Right'), ('rtl', 'Right-to-Left')], default='ltr', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('translation', models.TextField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('translation_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.language')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=255)),
                ('pos', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adj', 'Adjective'), ('adv', 'Adverb'), ('phrase', 'Phrase'), ('prep', 'Preposition')], max_length=20)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='lexicon.concept')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.language')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField()),
                ('linked_examples', models.ManyToManyField(blank=True, to='lexicon.example')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definition', to='lexicon.word')),
            ],
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('language', 'text', 'pos'), name='unique_word_per_language_pos'),
        ),
    ]
