# Generated by Django 6.0.2 on 2026-02-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='semantic_key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
