# Generated by Django 6.0.2 on 2026-02-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0002_concept_semantic_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='semantic_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
